"""
Visualization API endpoint for the Project Intelligence Hub.

Accepts natural language queries and returns chart configurations
generated by the VisualizationGenerator service.
"""

import logging

from fastapi import APIRouter, HTTPException, status

from models.schemas import ChartConfig, VisualizationRequest
from services.visualization import VisualizationGenerator

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/visualize", response_model=ChartConfig)
def generate_visualization(request: VisualizationRequest):
    """
    Generate a chart configuration from a natural language query.

    Accepts a query describing the desired visualization, retrieves relevant
    data from the vector store, and uses the LLM to produce a chart config.

    Returns 400 if the query is empty.
    Returns 422 if visualization generation fails due to invalid input or parsing errors.
    Returns 503 if an external service (Groq API, ChromaDB) is unavailable.
    """
    # Validate that query is not empty or whitespace
    if not request.query or not request.query.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Visualization query cannot be empty.",
        )

    try:
        generator = VisualizationGenerator()
        chart_config = generator.generate(request.query)
        return chart_config
    except ValueError as e:
        logger.warning(f"Visualization generation failed (ValueError): {e}")
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e),
        )
    except RuntimeError as e:
        logger.error(f"Visualization generation failed (RuntimeError): {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(e),
        )
