"""
Discovery data structure schemas.

Defines typed schemas for discovery engine outputs including
PostgreSQL table metadata, MongoDB collection metadata,
semantic profiling results, and document profiles.
"""

from pydantic import BaseModel, Field


class PostgresColumnInfo(BaseModel):
    """Schema for a PostgreSQL column discovered during introspection."""

    name: str
    data_type: str
    nullable: bool
    is_primary_key: bool
    default_value: str | None = None


class ForeignKeyInfo(BaseModel):
    """Schema for a foreign key relationship between tables."""

    column: str
    references_table: str
    references_column: str


class IndexInfo(BaseModel):
    """Schema for a database index."""

    name: str
    columns: list[str] = Field(default_factory=list)
    is_unique: bool = False


class PostgresTableInfo(BaseModel):
    """Schema for a discovered PostgreSQL table or view."""

    schema_name: str
    table_name: str
    table_type: str = Field(
        description="Object type: table or view"
    )
    columns: list[PostgresColumnInfo] = Field(default_factory=list)
    primary_key: list[str] = Field(default_factory=list)
    foreign_keys: list[ForeignKeyInfo] = Field(default_factory=list)
    indexes: list[IndexInfo] = Field(default_factory=list)
    row_count_estimate: int | None = None


class MongoFieldInfo(BaseModel):
    """Schema for a MongoDB field inferred from document sampling."""

    name: str
    field_path: str = Field(
        description="Dot-notation path for nested fields"
    )
    inferred_type: str
    nullable: bool
    is_nested: bool = False
    nesting_depth: int = 0


class MongoCollectionInfo(BaseModel):
    """Schema for a discovered MongoDB collection."""

    database_name: str
    collection_name: str
    inferred_fields: list[MongoFieldInfo] = Field(default_factory=list)
    document_count_estimate: int | None = None
    sample_size: int = 0


class SemanticFieldInfo(BaseModel):
    """Schema for a field's semantic profile."""

    technical_name: str
    semantic_label: str = Field(
        description="Human-friendly label (e.g., 'actl_exp' → 'actual_cost')"
    )
    description: str
    is_identifier: bool = False
    is_project_field: bool = False


class SemanticProfile(BaseModel):
    """Schema for semantic metadata generated by the profiler.

    Contains business-friendly names, descriptions, domain tags,
    query capabilities, and suggested questions for a discovered object.
    """

    semantic_name: str = Field(
        description="Human-friendly name (e.g., 'Project Financials')"
    )
    description: str
    domain_tags: list[str] = Field(default_factory=list)
    important_fields: list[SemanticFieldInfo] = Field(default_factory=list)
    query_capabilities: list[str] = Field(default_factory=list)
    suggested_questions: list[str] = Field(default_factory=list)
    confidence: str = Field(
        default="medium",
        description="Confidence level: high, medium, or low",
    )
    project_fields: list[str] = Field(default_factory=list)


class DocumentProfile(BaseModel):
    """Schema for a discovered document's profile.

    Represents semantic metadata extracted from ingested documents
    (PDF, DOCX, TXT, CSV, Excel, JSON) for catalog integration.
    """

    file_name: str
    document_type: str = Field(
        description="File type: pdf, docx, txt, csv, xlsx, json"
    )
    domain_tags: list[str] = Field(default_factory=list)
    description: str = ""
    sections: list[str] | None = None
    page_count: int | None = None
    has_structured_data: bool = False
