"""Resize embedding vector column from 1536 to 384 dimensions.

Revision ID: 003
Revises: 002
Create Date: 2026-08-26

Switches from the OpenAI ada-002 dimension (1536) to the local
sentence-transformers all-MiniLM-L6-v2 model (384 dimensions).

Existing embeddings are dropped and recreated since:
1. Old data was generated by a mock/deterministic stub (not real embeddings)
2. The vector dimension cannot be altered in-place with pgvector

After this migration, re-index any documents to generate real embeddings.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# Revision identifiers used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_DIMENSION = 384
OLD_DIMENSION = 1536


def upgrade() -> None:
    """Drop and recreate embeddings table with 384-dim vector column."""

    # Drop the old embeddings table (cascade from chunks handles FK)
    op.drop_table("embeddings")

    # Recreate with new dimension
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "chunk_id",
            sa.Uuid(),
            sa.ForeignKey("document_chunks.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column("embedding", Vector(NEW_DIMENSION), nullable=False),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )


def downgrade() -> None:
    """Revert to 1536-dim vector column."""

    op.drop_table("embeddings")

    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "chunk_id",
            sa.Uuid(),
            sa.ForeignKey("document_chunks.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column("embedding", Vector(OLD_DIMENSION), nullable=False),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
